export const WeatherArray: [string, string, { en: [string, string], ja: [string, string], zh_cn: [string, string], ar: [string, string], ru: [string, string], es: [string, string], fr: [string, string] }][] = [
  ["200", "11d", { en: ["Thunderstorm", "thunderstorm with light rain"], ja: ["雷雨", "小雨を伴う雷雨"], zh_cn: ["雷暴", "伴有小雨的雷暴"], ar: ["عاصفة رعدية", "عاصفة رعدية مع مطر خفيف"], ru: ["Гроза", "гроза с небольшим дождём"], es: ["Tormenta", "tormenta con lluvia ligera"], fr: ["Orage", "orage avec pluie légère"] }],
  ["201", "11d", { en: ["Thunderstorm", "thunderstorm with rain"], ja: ["雷雨", "雨を伴う雷雨"], zh_cn: ["雷暴", "伴有雨的雷暴"], ar: ["عاصفة رعدية", "عاصفة رعدية مع مطر"], ru: ["Гроза", "гроза с дождём"], es: ["Tormenta", "tormenta con lluvia"], fr: ["Orage", "orage avec pluie"] }],
  ["202", "11d", { en: ["Thunderstorm", "thunderstorm with heavy rain"], ja: ["雷雨", "大雨を伴う雷雨"], zh_cn: ["雷暴", "伴有大雨的雷暴"], ar: ["عاصفة رعدية", "عاصفة رعدية مع مطر غزير"], ru: ["Гроза", "гроза с сильным дождём"], es: ["Tormenta", "tormenta con lluvia intensa"], fr: ["Orage", "orage avec pluie forte"] }],
  ["210", "11d", { en: ["Thunderstorm", "light thunderstorm"], ja: ["雷雨", "弱い雷雨"], zh_cn: ["雷暴", "轻雷暴"], ar: ["عاصفة رعدية", "عاصفة رعدية خفيفة"], ru: ["Гроза", "слабая гроза"], es: ["Tormenta", "tormenta ligera"], fr: ["Orage", "orage léger"] }],
  ["211", "11d", { en: ["Thunderstorm", "thunderstorm"], ja: ["雷雨", "雷雨"], zh_cn: ["雷暴", "雷暴"], ar: ["عاصفة رعدية", "عاصفة رعدية"], ru: ["Гроза", "гроза"], es: ["Tormenta", "tormenta"], fr: ["Orage", "orage"] }],
  ["212", "11d", { en: ["Thunderstorm", "heavy thunderstorm"], ja: ["雷雨", "激しい雷雨"], zh_cn: ["雷暴", "强雷暴"], ar: ["عاصفة رعدية", "عاصفة رعدية شديدة"], ru: ["Гроза", "сильная гроза"], es: ["Tormenta", "tormenta intensa"], fr: ["Orage", "orage violent"] }],
  ["221", "11d", { en: ["Thunderstorm", "ragged thunderstorm"], ja: ["雷雨", "断続的な雷雨"], zh_cn: ["雷暴", "不规则雷暴"], ar: ["عاصفة رعدية", "عاصفة رعدية متقطعة"], ru: ["Гроза", "неравномерная гроза"], es: ["Tormenta", "tormenta irregular"], fr: ["Orage", "orage irrégulier"] }],
  ["230", "11d", { en: ["Thunderstorm", "thunderstorm with light drizzle"], ja: ["雷雨", "霧雨を伴う雷雨（弱）"], zh_cn: ["雷暴", "伴有小毛毛雨的雷暴"], ar: ["عاصفة رعدية", "عاصفة رعدية مع رذاذ خفيف"], ru: ["Гроза", "гроза со слабой моросью"], es: ["Tormenta", "tormenta con llovizna ligera"], fr: ["Orage", "orage avec bruine légère"] }],
  ["231", "11d", { en: ["Thunderstorm", "thunderstorm with drizzle"], ja: ["雷雨", "霧雨を伴う雷雨"], zh_cn: ["雷暴", "伴有毛毛雨的雷暴"], ar: ["عاصفة رعدية", "عاصفة رعدية مع رذاذ"], ru: ["Гроза", "гроза с моросью"], es: ["Tormenta", "tormenta con llovizna"], fr: ["Orage", "orage avec bruine"] }],
  ["232", "11d", { en: ["Thunderstorm", "thunderstorm with heavy drizzle"], ja: ["雷雨", "強い霧雨を伴う雷雨"], zh_cn: ["雷暴", "伴有大毛毛雨的雷暴"], ar: ["عاصفة رعدية", "عاصفة رعدية مع رذاذ كثيف"], ru: ["Гроза", "гроза с сильной моросью"], es: ["Tormenta", "tormenta con llovizna intensa"], fr: ["Orage", "orage avec bruine forte"] }],
  ["300", "09d", { en: ["Drizzle", "light intensity drizzle"], ja: ["霧雨", "弱い霧雨"], zh_cn: ["毛毛雨", "小强度毛毛雨"], ar: ["رذاذ", "رذاذ خفيف"], ru: ["Морось", "слабая морось"], es: ["Llovizna", "llovizna ligera"], fr: ["Bruine", "bruine légère"] }],
  ["301", "09d", { en: ["Drizzle", "drizzle"], ja: ["霧雨", "霧雨"], zh_cn: ["毛毛雨", "毛毛雨"], ar: ["رذاذ", "رذاذ"], ru: ["Морось", "морось"], es: ["Llovizna", "llovizna"], fr: ["Bruine", "bruine"] }],
  ["302", "09d", { en: ["Drizzle", "heavy intensity drizzle"], ja: ["霧雨", "強い霧雨"], zh_cn: ["毛毛雨", "大强度毛毛雨"], ar: ["رذاذ", "رذاذ كثيف"], ru: ["Морось", "сильная морось"], es: ["Llovizna", "llovizna intensa"], fr: ["Bruine", "bruine forte"] }],
  ["310", "09d", { en: ["Drizzle", "light intensity drizzle rain"], ja: ["霧雨", "弱い霧雨混じりの雨"], zh_cn: ["毛毛雨", "小强度毛毛细雨"], ar: ["رذاذ", "مطر رذاذ خفيف"], ru: ["Морось", "слабый моросящий дождь"], es: ["Llovizna", "lluvia con llovizna ligera"], fr: ["Bruine", "pluie bruine légère"] }],
  ["311", "09d", { en: ["Drizzle", "drizzle rain"], ja: ["霧雨", "霧雨混じりの雨"], zh_cn: ["毛毛雨", "毛毛细雨"], ar: ["رذاذ", "مطر رذاذ"], ru: ["Морось", "моросящий дождь"], es: ["Llovizna", "lluvia con llovizna"], fr: ["Bruine", "pluie bruine"] }],
  ["312", "09d", { en: ["Drizzle", "heavy intensity drizzle rain"], ja: ["霧雨", "強い霧雨混じりの雨"], zh_cn: ["毛毛雨", "大强度毛毛细雨"], ar: ["رذاذ", "مطر رذاذ كثيف"], ru: ["Морось", "сильный моросящий дождь"], es: ["Llovizna", "lluvia con llovizna intensa"], fr: ["Bruine", "pluie bruine forte"] }],
  ["313", "09d", { en: ["Drizzle", "shower rain and drizzle"], ja: ["霧雨", "にわか雨と霧雨"], zh_cn: ["毛毛雨", "阵雨和毛毛雨"], ar: ["رذاذ", "زخات مطر ورذاذ"], ru: ["Морось", "ливень с моросью"], es: ["Llovizna", "lluvia y llovizna"], fr: ["Bruine", "averse et bruine"] }],
  ["314", "09d", { en: ["Drizzle", "heavy shower rain and drizzle"], ja: ["霧雨", "強いにわか雨と霧雨"], zh_cn: ["毛毛雨", "强阵雨和毛毛雨"], ar: ["رذاذ", "زخات مطر غزيرة ورذاذ"], ru: ["Морось", "сильный ливень с моросью"], es: ["Llovizna", "lluvia intensa y llovizna"], fr: ["Bruine", "averse forte et bruine"] }],
  ["321", "09d", { en: ["Drizzle", "shower drizzle"], ja: ["霧雨", "にわか霧雨"], zh_cn: ["毛毛雨", "阵毛毛雨"], ar: ["رذاذ", "زخات رذاذ"], ru: ["Морось", "ливневая морось"], es: ["Llovizna", "chubasco de llovizna"], fr: ["Bruine", "averse de bruine"] }],
  ["500", "10d", { en: ["Rain", "light rain"], ja: ["雨", "小雨"], zh_cn: ["雨", "小雨"], ar: ["مطر", "مطر خفيف"], ru: ["Дождь", "небольшой дождь"], es: ["Lluvia", "lluvia ligera"], fr: ["Pluie", "pluie légère"] }],
  ["501", "10d", { en: ["Rain", "moderate rain"], ja: ["雨", "並の雨"], zh_cn: ["雨", "中雨"], ar: ["مطر", "مطر معتدل"], ru: ["Дождь", "умеренный дождь"], es: ["Lluvia", "lluvia moderada"], fr: ["Pluie", "pluie modérée"] }],
  ["502", "10d", { en: ["Rain", "heavy intensity rain"], ja: ["雨", "強い雨"], zh_cn: ["雨", "大雨"], ar: ["مطر", "مطر غزير"], ru: ["Дождь", "сильный дождь"], es: ["Lluvia", "lluvia intensa"], fr: ["Pluie", "pluie forte"] }],
  ["503", "10d", { en: ["Rain", "very heavy rain"], ja: ["雨", "非常に強い雨"], zh_cn: ["雨", "暴雨"], ar: ["مطر", "مطر غزير جداً"], ru: ["Дождь", "очень сильный дождь"], es: ["Lluvia", "lluvia muy intensa"], fr: ["Pluie", "pluie très forte"] }],
  ["504", "10d", { en: ["Rain", "extreme rain"], ja: ["雨", "猛烈な雨"], zh_cn: ["雨", "极端大雨"], ar: ["مطر", "مطر شديد للغاية"], ru: ["Дождь", "экстремальный дождь"], es: ["Lluvia", "lluvia extrema"], fr: ["Pluie", "pluie extrême"] }],
  ["511", "13d", { en: ["Rain", "freezing rain"], ja: ["雨", "凍雨"], zh_cn: ["雨", "冻雨"], ar: ["مطر", "مطر متجمد"], ru: ["Дождь", "ледяной дождь"], es: ["Lluvia", "lluvia helada"], fr: ["Pluie", "pluie verglaçante"] }],
  ["520", "09d", { en: ["Rain", "light intensity shower rain"], ja: ["雨", "弱いにわか雨"], zh_cn: ["雨", "小阵雨"], ar: ["مطر", "زخات مطر خفيفة"], ru: ["Дождь", "слабый ливень"], es: ["Lluvia", "chubasco ligero"], fr: ["Pluie", "averse légère"] }],
  ["521", "09d", { en: ["Rain", "shower rain"], ja: ["雨", "にわか雨"], zh_cn: ["雨", "阵雨"], ar: ["مطر", "زخات مطر"], ru: ["Дождь", "ливень"], es: ["Lluvia", "chubasco"], fr: ["Pluie", "averse"] }],
  ["522", "09d", { en: ["Rain", "heavy intensity shower rain"], ja: ["雨", "強いにわか雨"], zh_cn: ["雨", "强阵雨"], ar: ["مطر", "زخات مطر غزيرة"], ru: ["Дождь", "сильный ливень"], es: ["Lluvia", "chubasco intenso"], fr: ["Pluie", "averse forte"] }],
  ["531", "09d", { en: ["Rain", "ragged shower rain"], ja: ["雨", "断続的なにわか雨"], zh_cn: ["雨", "不规则阵雨"], ar: ["مطر", "زخات مطر متقطعة"], ru: ["Дождь", "неравномерный ливень"], es: ["Lluvia", "chubasco irregular"], fr: ["Pluie", "averse irrégulière"] }],
  ["600", "13d", { en: ["Snow", "light snow"], ja: ["雪", "小雪"], zh_cn: ["雪", "小雪"], ar: ["ثلج", "ثلج خفيف"], ru: ["Снег", "небольшой снег"], es: ["Nieve", "nieve ligera"], fr: ["Neige", "neige légère"] }],
  ["601", "13d", { en: ["Snow", "snow"], ja: ["雪", "雪"], zh_cn: ["雪", "雪"], ar: ["ثلج", "ثلج"], ru: ["Снег", "снег"], es: ["Nieve", "nieve"], fr: ["Neige", "neige"] }],
  ["602", "13d", { en: ["Snow", "heavy snow"], ja: ["雪", "大雪"], zh_cn: ["雪", "大雪"], ar: ["ثلج", "ثلج كثيف"], ru: ["Снег", "сильный снег"], es: ["Nieve", "nieve intensa"], fr: ["Neige", "neige forte"] }],
  ["611", "13d", { en: ["Snow", "sleet"], ja: ["雪", "みぞれ"], zh_cn: ["雪", "雨夹雪"], ar: ["ثلج", "مطر ثلجي"], ru: ["Снег", "мокрый снег"], es: ["Nieve", "aguanieve"], fr: ["Neige", "grésil"] }],
  ["612", "13d", { en: ["Snow", "light shower sleet"], ja: ["雪", "弱いにわかみぞれ"], zh_cn: ["雪", "小阵雨夹雪"], ar: ["ثلج", "زخات مطر ثلجي خفيفة"], ru: ["Снег", "слабый ливневый мокрый снег"], es: ["Nieve", "chubasco de aguanieve ligero"], fr: ["Neige", "averse de grésil légère"] }],
  ["613", "13d", { en: ["Snow", "shower sleet"], ja: ["雪", "にわかみぞれ"], zh_cn: ["雪", "阵雨夹雪"], ar: ["ثلج", "زخات مطر ثلجي"], ru: ["Снег", "ливневый мокрый снег"], es: ["Nieve", "chubasco de aguanieve"], fr: ["Neige", "averse de grésil"] }],
  ["615", "13d", { en: ["Snow", "light rain and snow"], ja: ["雪", "雨と雪（弱）"], zh_cn: ["雪", "小雨夹雪"], ar: ["ثلج", "مطر خفيف وثلج"], ru: ["Снег", "небольшой дождь со снегом"], es: ["Nieve", "lluvia ligera y nieve"], fr: ["Neige", "pluie légère et neige"] }],
  ["616", "13d", { en: ["Snow", "rain and snow"], ja: ["雪", "雨と雪"], zh_cn: ["雪", "雨夹雪"], ar: ["ثلج", "مطر وثلج"], ru: ["Снег", "дождь со снегом"], es: ["Nieve", "lluvia y nieve"], fr: ["Neige", "pluie et neige"] }],
  ["620", "13d", { en: ["Snow", "light shower snow"], ja: ["雪", "弱いにわか雪"], zh_cn: ["雪", "小阵雪"], ar: ["ثلج", "زخات ثلج خفيفة"], ru: ["Снег", "слабый ливневый снег"], es: ["Nieve", "chubasco de nieve ligero"], fr: ["Neige", "averse de neige légère"] }],
  ["621", "13d", { en: ["Snow", "shower snow"], ja: ["雪", "にわか雪"], zh_cn: ["雪", "阵雪"], ar: ["ثلج", "زخات ثلج"], ru: ["Снег", "ливневый снег"], es: ["Nieve", "chubasco de nieve"], fr: ["Neige", "averse de neige"] }],
  ["622", "13d", { en: ["Snow", "heavy shower snow"], ja: ["雪", "強いにわか雪"], zh_cn: ["雪", "强阵雪"], ar: ["ثلج", "زخات ثلج كثيفة"], ru: ["Снег", "сильный ливневый снег"], es: ["Nieve", "chubasco de nieve intenso"], fr: ["Neige", "averse de neige forte"] }],
  ["701", "50d", { en: ["Mist", "mist"], ja: ["霧", "薄霧"], zh_cn: ["薄雾", "薄雾"], ar: ["ضباب خفيف", "ضباب خفيف"], ru: ["Туман", "лёгкий туман"], es: ["Neblina", "neblina"], fr: ["Brume", "brume"] }],
  ["711", "50d", { en: ["Smoke", "smoke"], ja: ["煙", "煙"], zh_cn: ["烟", "烟"], ar: ["دخان", "دخان"], ru: ["Дым", "дым"], es: ["Humo", "humo"], fr: ["Fumée", "fumée"] }],
  ["721", "50d", { en: ["Haze", "haze"], ja: ["霞", "霞"], zh_cn: ["霾", "霾"], ar: ["ضباب دخاني", "ضباب دخاني"], ru: ["Мгла", "мгла"], es: ["Neblina", "neblina seca"], fr: ["Brume sèche", "brume sèche"] }],
  ["731", "50d", { en: ["Dust", "sand/dust whirls"], ja: ["砂塵", "砂塵旋風"], zh_cn: ["沙尘", "沙尘旋风"], ar: ["غبار", "عواصف رملية/غبارية"], ru: ["Пыль", "песчаные/пылевые вихри"], es: ["Polvo", "remolinos de arena/polvo"], fr: ["Poussière", "tourbillons de sable/poussière"] }],
  ["741", "50d", { en: ["Fog", "fog"], ja: ["霧", "霧"], zh_cn: ["雾", "雾"], ar: ["ضباب", "ضباب"], ru: ["Туман", "туман"], es: ["Niebla", "niebla"], fr: ["Brouillard", "brouillard"] }],
  ["751", "50d", { en: ["Sand", "sand"], ja: ["砂", "砂"], zh_cn: ["沙", "沙"], ar: ["رمال", "رمال"], ru: ["Песок", "песок"], es: ["Arena", "arena"], fr: ["Sable", "sable"] }],
  ["761", "50d", { en: ["Dust", "dust"], ja: ["砂塵", "砂塵"], zh_cn: ["沙尘", "沙尘"], ar: ["غبار", "غبار"], ru: ["Пыль", "пыль"], es: ["Polvo", "polvo"], fr: ["Poussière", "poussière"] }],
  ["762", "50d", { en: ["Ash", "volcanic ash"], ja: ["火山灰", "火山灰"], zh_cn: ["火山灰", "火山灰"], ar: ["رماد بركاني", "رماد بركاني"], ru: ["Пепел", "вулканический пепел"], es: ["Ceniza", "ceniza volcánica"], fr: ["Cendres", "cendres volcaniques"] }],
  ["771", "50d", { en: ["Squall", "squalls"], ja: ["スコール", "スコール"], zh_cn: ["飑", "飑"], ar: ["عاصفة مفاجئة", "عواصف مفاجئة"], ru: ["Шквал", "шквалы"], es: ["Chubasco", "chubascos"], fr: ["Grain", "grains"] }],
  ["781", "50d", { en: ["Tornado", "tornado"], ja: ["竜巻", "竜巻"], zh_cn: ["龙卷风", "龙卷风"], ar: ["إعصار", "إعصار"], ru: ["Торнадо", "торнадо"], es: ["Tornado", "tornado"], fr: ["Tornade", "tornade"] }],
  ["800", "01d", { en: ["Clear", "clear sky"], ja: ["晴れ", "快晴"], zh_cn: ["晴", "晴空"], ar: ["صافٍ", "سماء صافية"], ru: ["Ясно", "ясное небо"], es: ["Despejado", "cielo despejado"], fr: ["Dégagé", "ciel dégagé"] }],
  ["801", "02d", { en: ["Clouds", "few clouds: 11-25%"], ja: ["晴れ", "薄曇り: 11-25%"], zh_cn: ["多云", "少云: 11-25%"], ar: ["غائم", "غيوم قليلة: 11-25%"], ru: ["Облачно", "малооблачно: 11-25%"], es: ["Nubes", "pocas nubes: 11-25%"], fr: ["Nuages", "peu nuageux: 11-25%"] }],
  ["802", "03d", { en: ["Clouds", "scattered clouds: 25-50%"], ja: ["曇り", "まばらな雲: 25-50%"], zh_cn: ["多云", "散云: 25-50%"], ar: ["غائم", "غيوم متفرقة: 25-50%"], ru: ["Облачно", "переменная облачность: 25-50%"], es: ["Nubes", "nubes dispersas: 25-50%"], fr: ["Nuages", "nuages épars: 25-50%"] }],
  ["803", "04d", { en: ["Clouds", "broken clouds: 51-84%"], ja: ["曇り", "曇り: 51-84%"], zh_cn: ["阴", "多云: 51-84%"], ar: ["غائم", "غيوم متقطعة: 51-84%"], ru: ["Облачно", "облачно с прояснениями: 51-84%"], es: ["Nubes", "nubes rotas: 51-84%"], fr: ["Nuages", "nuages fragmentés: 51-84%"] }],
  ["804", "04d", { en: ["Clouds", "overcast clouds: 85-100%"], ja: ["曇り", "厚い曇り: 85-100%"], zh_cn: ["阴", "阴天: 85-100%"], ar: ["غائم", "غيوم كثيفة: 85-100%"], ru: ["Облачно", "пасмурно: 85-100%"], es: ["Nubes", "nublado: 85-100%"], fr: ["Nuages", "couvert: 85-100%"] }]
];




export const Icons:{[key:string]: string} = {
"11d" : "/images/11d_t.png", 
"09d" : "/images/09d_t.png", 
"10d" : "/images/10d_t.png",
"10n" : "/images/10n_t.png",
"11n" : "/images/11n_t.png", 
"13d" : "/images/13d_t.png",
"13n" : "/images/13n_t.png", 
"01d" : "/images/01d_t.png", 
"01n" : "/images/01n_t.png", 
"02d" : "/images/02d_t.png", 
"02n" : "/images/02n_t.png", 
"03d" : "/images/03d_t.png", 
"03n" : "/images/03n_t.png", 
"04d" : "/images/04d_t.png", 
"04n" : "/images/04n_t.png",
"50d" : "/images/50d_t.png",
"50n" : "/images/50n_t.png" 
}     
